### ISSUE TITLE
Node Request

### ISSUE THREAD

**Issue by Neuffexx** [blockout22/OverwatchVisualScripting#11]
I noticed when porting the project that Player variables are in essence treated as global variables and default to 'Event Player' selection for whom to grab the variable from.
This unfortunately means that you dont have control over who to grab the variable from, in this example its as simple as the host player, which is a pre-determiend setting, but I could also (in the workshop) provide a player reference I have stored in a variable.
Please create a new seperate node for Player / Global Variable, allowing the player variable to take in a 'player' input to work.
This could be doen similar to the 'Team' node, where you provide the list of options that the workshop has, so that it can be used as an input, or we could alternatively provide our own player reference, via a variable.

Workshop example:
![image](https://github.com/blockout22/OverwatchVisualScripting/assets/63469833/23de71c5-d14a-46d1-8677-0d5271a295ff)
In script attempted mirror / usage (defaults to _Event_): 
![image](https://github.com/blockout22/OverwatchVisualScripting/assets/63469833/827539fd-3ebb-47e9-96d3-c6d222bb9fee)

Example Visualization:
![image](https://github.com/blockout22/OverwatchVisualScripting/assets/63469833/01183212-53f7-4155-aad7-cc286cd20ddb)

**Comment by blockout22** [comment]
![image](https://github.com/blockout22/OverwatchVisualScripting/assets/4086993/ff052b24-e48f-4023-9cb8-0dd3bf337e99)

I think I have implemented these right

I have also kept the Get Variable Node and created a Get node for both player and global variables 

it's also funny because I left my self a note months ago when I first created the Get Variable Node 
![image](https://github.com/blockout22/OverwatchVisualScripting/assets/4086993/8491b8eb-4256-456f-9c63-d974c67bceb1)

**Comment by Neuffexx** [comment]
Haha, working nicely.
Makes sense, no need to remove the general one.
Especially since 'Event' is the most common one.
